Add 1Password SDK dependency for Alpine Linux
The 1Password OpenTofu provider v3 errors after init on Spacelift:

```
Error: failed to read provider configuration schema for
registry.opentofu.org/1password/onepassword: failed to instantiate
provider "registry.opentofu.org/1password/onepassword" to obtain schema:
fork/exec
.terraform/providers/registry.opentofu.org/1password/onepassword/3.2.1/linux_amd64/terraform-provider-onepassword_v3.2.1:
no such file or directory
```

The Spacelift runner image is built on Alpine Linux. Although the
1Password provider no longer requires the 1Password CLI, a custom runner
image is still needed because the 1Password SDK requires additional
dependencies on Alpine Linux.

- https://github.com/1Password/terraform-provider-onepassword/issues/228
- https://github.com/1Password/terraform-provider-onepassword/issues/340
- https://github.com/1Password/terraform-provider-onepassword/releases/tag/v3.0.0
- https://github.com/spacelift-io/runner-terraform
- https://pkgs.alpinelinux.org/package/edge/main/x86_64/gcompat
- https://git.adelielinux.org/adelie/gcompat